{% set name = "ldc" %}
{% set version = "1.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ldc-developers/ldc/releases/download/v{{ version }}/ldc-{{ version }}-src.tar.gz       # [unix]
  sha256: 426d9d0dc65b7d3d739809c9c8bf022177aeaa8e65999be7145e052be3357302  # [unix]

  # Use the pre-built binaries for windows.
  url: https://github.com/ldc-developers/ldc/releases/download/v{{ version }}/ldc2-{{ version }}-windows-x64.7z  # [win]
  sha256: a023607f8ce2702006646ea2918a482f7c1b553f9fa5184346151a95680622d3  # [win]

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
    build:
      - {{ compiler('c') }}      # [unix]
      - {{ compiler('cxx') }}    # [unix]
      - git                      # [unix]
      - cmake                    # [unix]
      - ninja                    # [unix]
      - 7za                      # [win]
    host:
      - libconfig                # [unix]
      - libedit                  # [unix]
      - ncurses                  # [unix]
      - curl                     # [unix]
      - llvmdev                  # [unix]

test:
  commands:
    - ldc2 --version

about:
  home: https://github.com/ldc-developers/ldc
  license: BSD, MIT, LDC
  license_file: LICENSE                                  # [unix]
  license_file: ldc2-{{ version }}-windows-x64\LICENSE   # [win]
  summary: 'The LLVM-based D Compiler'

  description: |
    The LDC project provides a portable D programming language compiler with modern optimization and code generation capabilities.
    The compiler uses the official DMD frontend to support the latest version of D2, and relies on the LLVM Core libraries for code generation.
  doc_url: https://wiki.dlang.org/LDC
  dev_url: https://github.com/ldc-developers/ldc 

extra:
  recipe-maintainers:
    - brainstorm
